university_abbrevations = {
    "itu": "istanbul teknik üniversitesi",
    "itü": "istanbul teknik üniversitesi",
    "odtu": "orta doğu teknik üniversitesi",
    "odtü": "orta doğu teknik üniversitesi",
    "metu": "orta doğu teknik üniversitesi",
    "bogazici": "boğaziçi üniversitesi",
    "boğaziçi": "boğaziçi üniversitesi",
    "boun": "boğaziçi üniversitesi",
    "iü": "istanbul üniversitesi",
    "marmara": "marmara üniversitesi",
    "gsu": "galatasaray üniversitesi",
    "yildiz": "yıldız teknik üniversitesi",
    "yıldız": "yıldız teknik üniversitesi",
    "ytü": "yıldız teknik üniversitesi",
    "yeditepe": "yeditepe üniversitesi",
    "hacettepe": "hacettepe üniversitesi",
    "ankara": "ankara üniversitesi",
    "ege": "ege üniversitesi",
    "dokuzeylul": "dokuz eylül üniversitesi",
    "selcuk": "selçuk üniversitesi",
    "uludag": "uludağ üniversitesi",
    "cbu": "manisa celal bayar üniversitesi",
    "ktu": "karadeniz teknik üniversitesi",
    "ata": "atatürk üniversitesi",
    "erciyes": "erciyes üniversitesi",
    "cbu": "celal bayar üniversitesi",
    "sdu": "süleyman demirel üniversitesi",
    "pau": "pamukkale üniversitesi",
    "omu": "ondokuz mayıs üniversitesi",
    "cumhuriyet": "cumhuriyet üniversitesi",
    "adnanmenderes": "aydın adnan menderes üniversitesi",
    "balikesir": "balıkesir üniversitesi",
    "cankaya": "çankaya üniversitesi",
    "baskent": "başkent üniversitesi",
    "bilkent": "bilkent üniversitesi",
    "koc": "koç üniversitesi",
    "koç": "koç üniversitesi",
    "sabanci": "sabancı üniversitesi",
    "sabancı": "sanabncı üniversitesi",
    "ozu": "özyeğin üniversitesi",
    "ozü": "özyeğin üniversitesi",
    "ieu": "izmir ekonomi üniversitesi",
    "tobb": "tobb ekonomi ve teknoloji üniversitesi",
    "isikun": "ışık üniversitesi",
    "bahcesehir": "bahçeşehir üniversitesi",
    "yasar": "yaşar üniversitesi",
    "gedik": "gedik üniversitesi",
    "gelisim": "istanbul gelişim üniversitesi",
    "beykent": "beykent üniversitesi",
    "uskudar": "üsküdar üniversitesi"
}